## Write a function so that the columns of the output matrix are powers of the input vector.

In [1]:
import numpy as np
x = np.array([1,2,3,4,5])
n = 3
matrix = np.column_stack([x**(n-i-1) for i in range(n)])
print(matrix)

[[ 1  1  1]
 [ 4  2  1]
 [ 9  3  1]
 [16  4  1]
 [25  5  1]]


## Write a function to find moving average in an array over a window.

In [2]:
input_list = [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
n = 3
def averagefinder(input_list,n):
    seq = len(input_list)-n+1
    print('The sequence values are : ')
    for i in range(seq):
        num1 = input_list[0+i:n+i]
        res = 0
        for j in range(0,len(num1)):
            res = res+num1[j]
            res1 = res/n
        print(res1)
    print('Length of the sequence is: ',seq)
    
averagefinder(input_list,n)

The sequence values are : 
5.0
4.666666666666667
5.666666666666667
6.666666666666667
9.666666666666666
28.666666666666668
49.333333333333336
72.66666666666667
84.0
93.33333333333333
116.33333333333333
Length of the sequence is:  11
